### PR TITLE
Fix hardcoded iron curtain stats

### LINKED ISSUE #115: Iron Curtain stats incorrect in JSON file

### PR DESCRIPTION
**Pull request by Blaarkies**
fix #115 
with Iron Curtain construction score not added bug fixed

### CODE REVIEW

File: game-engine/core/src/main/java/za/co/entelect/challenge/core/entities/GameDetails.java [hunk 1]
```diff
@@ -43,9 +43,9 @@ public GameDetails(int round) {
...
                 .forEach(bt -> buildingsStats.put(bt, BuildingFactory.createBuildingStats(bt)));
 
-        ironCurtainStats.put("price", 150);
-        ironCurtainStats.put("activeRounds", 6);
-        ironCurtainStats.put("resetPeriod", 50);
-        ironCurtainStats.put("constructionScore", 20);
+        ironCurtainStats.put("price", GameConfig.getIroncurtainPrice());
+        ironCurtainStats.put("activeRounds", GameConfig.getIroncurtainActiveRounds());
+        ironCurtainStats.put("resetPeriod", GameConfig.getIroncurtainResetPeriod());
+        ironCurtainStats.put("constructionScore", GameConfig.getIroncurtainConstructionScore());
```
Comment (DaanKeun) [inline game-engine/core/src/main/java/za/co/entelect/challenge/core/entities/GameDetails.java]: Have we updated the GameConfig file with these added setting in a previous PR?

Comment (Blaarkies) [reply game-engine/core/src/main/java/za/co/entelect/challenge/core/entities/GameDetails.java]: Yes. the gameconfig had them before, but I missed this part as I tested the json capability, forgot to finalize this part
